// Generated by gencpp from file osuf1_common/MPC_metadata.msg
// DO NOT EDIT!


#ifndef OSUF1_COMMON_MESSAGE_MPC_METADATA_H
#define OSUF1_COMMON_MESSAGE_MPC_METADATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace osuf1_common
{
template <class ContainerAllocator>
struct MPC_metadata_
{
  typedef MPC_metadata_<ContainerAllocator> Type;

  MPC_metadata_()
    : header()
    , dt(0.0)
    , horizon(0.0)  {
    }
  MPC_metadata_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , dt(0.0)
    , horizon(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _dt_type;
  _dt_type dt;

   typedef float _horizon_type;
  _horizon_type horizon;





  typedef boost::shared_ptr< ::osuf1_common::MPC_metadata_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::osuf1_common::MPC_metadata_<ContainerAllocator> const> ConstPtr;

}; // struct MPC_metadata_

typedef ::osuf1_common::MPC_metadata_<std::allocator<void> > MPC_metadata;

typedef boost::shared_ptr< ::osuf1_common::MPC_metadata > MPC_metadataPtr;
typedef boost::shared_ptr< ::osuf1_common::MPC_metadata const> MPC_metadataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::osuf1_common::MPC_metadata_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::osuf1_common::MPC_metadata_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::osuf1_common::MPC_metadata_<ContainerAllocator1> & lhs, const ::osuf1_common::MPC_metadata_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.dt == rhs.dt &&
    lhs.horizon == rhs.horizon;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::osuf1_common::MPC_metadata_<ContainerAllocator1> & lhs, const ::osuf1_common::MPC_metadata_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace osuf1_common

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::osuf1_common::MPC_metadata_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::osuf1_common::MPC_metadata_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::osuf1_common::MPC_metadata_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::osuf1_common::MPC_metadata_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::osuf1_common::MPC_metadata_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::osuf1_common::MPC_metadata_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::osuf1_common::MPC_metadata_<ContainerAllocator> >
{
  static const char* value()
  {
    return "befeb0e614663929d01d1f82336001db";
  }

  static const char* value(const ::osuf1_common::MPC_metadata_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbefeb0e614663929ULL;
  static const uint64_t static_value2 = 0xd01d1f82336001dbULL;
};

template<class ContainerAllocator>
struct DataType< ::osuf1_common::MPC_metadata_<ContainerAllocator> >
{
  static const char* value()
  {
    return "osuf1_common/MPC_metadata";
  }

  static const char* value(const ::osuf1_common::MPC_metadata_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::osuf1_common::MPC_metadata_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float32 dt\n"
"float32 horizon\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::osuf1_common::MPC_metadata_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::osuf1_common::MPC_metadata_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.dt);
      stream.next(m.horizon);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MPC_metadata_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::osuf1_common::MPC_metadata_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::osuf1_common::MPC_metadata_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "dt: ";
    Printer<float>::stream(s, indent + "  ", v.dt);
    s << indent << "horizon: ";
    Printer<float>::stream(s, indent + "  ", v.horizon);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OSUF1_COMMON_MESSAGE_MPC_METADATA_H
