// Generated by gencpp from file osuf1_common/NPoint.msg
// DO NOT EDIT!


#ifndef OSUF1_COMMON_MESSAGE_NPOINT_H
#define OSUF1_COMMON_MESSAGE_NPOINT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace osuf1_common
{
template <class ContainerAllocator>
struct NPoint_
{
  typedef NPoint_<ContainerAllocator> Type;

  NPoint_()
    : p()  {
    }
  NPoint_(const ContainerAllocator& _alloc)
    : p(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _p_type;
  _p_type p;





  typedef boost::shared_ptr< ::osuf1_common::NPoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::osuf1_common::NPoint_<ContainerAllocator> const> ConstPtr;

}; // struct NPoint_

typedef ::osuf1_common::NPoint_<std::allocator<void> > NPoint;

typedef boost::shared_ptr< ::osuf1_common::NPoint > NPointPtr;
typedef boost::shared_ptr< ::osuf1_common::NPoint const> NPointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::osuf1_common::NPoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::osuf1_common::NPoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::osuf1_common::NPoint_<ContainerAllocator1> & lhs, const ::osuf1_common::NPoint_<ContainerAllocator2> & rhs)
{
  return lhs.p == rhs.p;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::osuf1_common::NPoint_<ContainerAllocator1> & lhs, const ::osuf1_common::NPoint_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace osuf1_common

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::osuf1_common::NPoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::osuf1_common::NPoint_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::osuf1_common::NPoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::osuf1_common::NPoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::osuf1_common::NPoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::osuf1_common::NPoint_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::osuf1_common::NPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a8139a50192c7dc7d77222a146aae12e";
  }

  static const char* value(const ::osuf1_common::NPoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa8139a50192c7dc7ULL;
  static const uint64_t static_value2 = 0xd77222a146aae12eULL;
};

template<class ContainerAllocator>
struct DataType< ::osuf1_common::NPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "osuf1_common/NPoint";
  }

  static const char* value(const ::osuf1_common::NPoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::osuf1_common::NPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] p\n"
;
  }

  static const char* value(const ::osuf1_common::NPoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::osuf1_common::NPoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.p);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NPoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::osuf1_common::NPoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::osuf1_common::NPoint_<ContainerAllocator>& v)
  {
    s << indent << "p[]" << std::endl;
    for (size_t i = 0; i < v.p.size(); ++i)
    {
      s << indent << "  p[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.p[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // OSUF1_COMMON_MESSAGE_NPOINT_H
