// Generated by gencpp from file osuf1_common/ReachSets.msg
// DO NOT EDIT!


#ifndef OSUF1_COMMON_MESSAGE_REACHSETS_H
#define OSUF1_COMMON_MESSAGE_REACHSETS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <osuf1_common/NPointSet.h>

namespace osuf1_common
{
template <class ContainerAllocator>
struct ReachSets_
{
  typedef ReachSets_<ContainerAllocator> Type;

  ReachSets_()
    : header()
    , sets()  {
    }
  ReachSets_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , sets(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::osuf1_common::NPointSet_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::osuf1_common::NPointSet_<ContainerAllocator> >> _sets_type;
  _sets_type sets;





  typedef boost::shared_ptr< ::osuf1_common::ReachSets_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::osuf1_common::ReachSets_<ContainerAllocator> const> ConstPtr;

}; // struct ReachSets_

typedef ::osuf1_common::ReachSets_<std::allocator<void> > ReachSets;

typedef boost::shared_ptr< ::osuf1_common::ReachSets > ReachSetsPtr;
typedef boost::shared_ptr< ::osuf1_common::ReachSets const> ReachSetsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::osuf1_common::ReachSets_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::osuf1_common::ReachSets_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::osuf1_common::ReachSets_<ContainerAllocator1> & lhs, const ::osuf1_common::ReachSets_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.sets == rhs.sets;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::osuf1_common::ReachSets_<ContainerAllocator1> & lhs, const ::osuf1_common::ReachSets_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace osuf1_common

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::osuf1_common::ReachSets_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::osuf1_common::ReachSets_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::osuf1_common::ReachSets_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::osuf1_common::ReachSets_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::osuf1_common::ReachSets_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::osuf1_common::ReachSets_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::osuf1_common::ReachSets_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6aec3e3fcb8a9e4d22874c0bd0b7379f";
  }

  static const char* value(const ::osuf1_common::ReachSets_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6aec3e3fcb8a9e4dULL;
  static const uint64_t static_value2 = 0x22874c0bd0b7379fULL;
};

template<class ContainerAllocator>
struct DataType< ::osuf1_common::ReachSets_<ContainerAllocator> >
{
  static const char* value()
  {
    return "osuf1_common/ReachSets";
  }

  static const char* value(const ::osuf1_common::ReachSets_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::osuf1_common::ReachSets_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"NPointSet[] sets\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: osuf1_common/NPointSet\n"
"NPoint[] set \n"
"================================================================================\n"
"MSG: osuf1_common/NPoint\n"
"float32[] p\n"
;
  }

  static const char* value(const ::osuf1_common::ReachSets_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::osuf1_common::ReachSets_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.sets);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ReachSets_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::osuf1_common::ReachSets_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::osuf1_common::ReachSets_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "sets[]" << std::endl;
    for (size_t i = 0; i < v.sets.size(); ++i)
    {
      s << indent << "  sets[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::osuf1_common::NPointSet_<ContainerAllocator> >::stream(s, indent + "    ", v.sets[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // OSUF1_COMMON_MESSAGE_REACHSETS_H
